### ISSUE TITLE
Add support for graded color support detection

### ISSUE THREAD

**Issue by sindresorhus** [chalk/supports-color-cli#1]
Like with https://github.com/chalk/supports-color/releases/tag/3.0.0

What's the best way to implement this in the CLI? Use different error codes? Output? Both?

// @Qix-

**Comment by Qix-** [comment]
Hmm, tricky. Error codes would be less than ideal; `0` means OK, and I don't think breaking that pattern is safe.

Output would probably be ideal; `0` (with error code `<>0`), and then `1`-`3` for specific level support (with error code `0`).

**Comment by jbnicolai** [comment]
How about level-specifying flags? By default, you're asking if it supports _any_ color.

`supports-color` with a `0` exit code means `supports any color`
`supports-color --256` with a `0` exit code means `supports 256 ansi color codes`
`supports-color --true` with a `0` exit code means `supports true-color`

**Comment by Qix-** [comment]
^ this. :+1:

**Comment by sindresorhus** [comment]
:+1: But flags should be consistent with the level names we use in the API.

**Comment by Qix-** [comment]
@sindresorhus you can't - not directly, at least. If we have the same arguments as what `supports-color` looks for, then you'll always return `0`.

**Comment by Qix-** [comment]
@sindresorhus *poke* close
