### ISSUE TITLE
Repo description is incorrect

### ISSUE THREAD

**Issue by JimSaiya** [chalk/supports-color-cli#3]
The description on this repo says "Check if a string has ANSI escape codes" instead of "Detect whether a terminal supports color".

**Comment by Qix-** [comment]
That it is. For clarity, it's the Github description field, not anything in the readme (I was looking around all confused for a minute).

@sindresorhus will have to change it. Thanks for the heads up! :dancer:

**Comment by JimSaiya** [comment]
NP.  I noticed it in the Repositories listing on the chalk organization page.  :smiley:

**Comment by sindresorhus** [comment]
Fixed. Thanks for noticing. No idea how that happened...

**Comment by JimSaiya** [comment]
Hey, it happens.  ;)
